FROM eclipse-temurin:21-jdk AS builder
WORKDIR /app
COPY . .
RUN echo "cache-bust-$(date +%s)" && chmod +x mvnw && ./mvnw clean package -DskipTests

FROM eclipse-temurin:21-jre
WORKDIR /app
COPY --from=builder /app/target/*.jar app.jar
ENTRYPOINT ["java", "-Dspring.profiles.active=prod", "-jar", "app.jar"]