spring:
  application:
    name: affkit-backend
  threads:
    virtual:
      enabled: true
  datasource:
    url: jdbc:postgresql://localhost:5433/affkit_db
    username: affkit
    password: affkit123
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          batch_size: 50
          time_zone: UTC
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
  data:
    redis:
      host: localhost
      port: 6379

resend:
  api-key: re_Y9jacGjq_Lnv6HVbXYS44ur458RdxrirP
  from: onboarding@resend.dev

app:
  frontend-url: http://localhost:3000
  jwt:
    secret: "affkit-super-secret-key-minimum-32-characters-long-for-hs256"
    access-token-ttl-seconds: 900
  session:
    refresh-token-ttl-days: 7

accesstrade:
  api-key: b1tnMBS5qwSWDQaL_IuY_mX5OoAhsY0K
  api-url: https://api.accesstrade.vn/v1/product_link/create
  campaigns:
    tiki: "4348614231480407268"
    lazada: "5087153089503673507"
    tiktok: "6648523843406889655"

server:
  port: 8080

jwt:
  secret: "affkit-super-secret-key-must-be-at-least-256-bits-long-for-hmac"
  access-token-expiry: 900
  refresh-token-expiry: 604800

logging:
  level:
    vn.affkit: DEBUG
    org.springframework.security: WARN
telegram:
  bot-token: 8785849009:AAHVhBLQqUITwHGvNXHxi8iLRKUBKG6QPFg
  bot-username: affkit_vn_bot